<a href="https://colab.research.google.com/github/yumi-kim/big_data_class/blob/master/%EC%BD%94%EB%94%A9%EC%88%98%EC%97%85_1%EC%9D%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# 변수

In [0]:
a = 'Kang Yang Jae'

In [0]:
a.split()

['Kang', 'Yang', 'Jae']

In [0]:
name = 'Kang Yang Jae'

In [0]:
name

'Kang Yang Jae'

In [0]:
age = 38

In [0]:
age

38

In [0]:
age + age 

76

In [0]:
name + name

'Kang Yang JaeKang Yang Jae'

In [0]:
height = 174.5

In [0]:
height

174.5

In [0]:
int(height)

174

In [0]:
height

174.5

In [0]:
height = int(height)

In [0]:
# 자료형

In [0]:
# list (리스트)

In [0]:
b = a.split()

In [0]:
b

['Kang', 'Yang', 'Jae']

In [0]:
b[0]

'Kang'

In [0]:
type(b[0])

str

In [0]:
b.append(age)

In [0]:
b[-1] # 맨뒷단을 부르는 인덱스 

38

In [0]:
b[-2] # 맨뒷단의 한칸 앞 

'Jae'

In [0]:
len(b)

4

In [0]:
len(a)

13

In [0]:
a

'Kang Yang Jae'

In [0]:
# numpy array 자료형 

In [0]:
import numpy as np

In [0]:
c = np.array([1,2,3,4,5,6,7,8,9])

In [0]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
d = [1,2,3,4,5,6,7,8,9]

In [0]:
d

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
d * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
e = c * 2

In [0]:
e * c

array([  2,   8,  18,  32,  50,  72,  98, 128, 162])

In [0]:
e

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
f = c.astype(float)

In [0]:
f.astype(int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# dictionary (사전)

In [0]:
dic = {  }

In [0]:
dic['key'] = 'value'

In [0]:
dic

{'key': 'value'}

In [0]:
dic['apple'] = '사과'

In [0]:
dic

{'apple': '사과', 'key': 'value'}

In [0]:
dic = {'apple' : '사과',
       'dog'   : '개',
       'cat'   : '고양이'
      }

In [0]:
dic['dog']

'개'

In [0]:
dic['cat']

'고양이'

In [0]:
dic['apple']

'사과'

In [0]:
# 반복문

In [0]:
b

['Kang', 'Yang', 'Jae', 38]

In [0]:
for n, each in enumerate(b):
  print(each,n)


Kang 0
Yang 1
Jae 2
38 3


In [0]:
for word in dic.keys():
  print("in English {word_e}, in Korean {word_k}".format(word_e=word, word_k=dic[word]))

in English apple, in Korean 사과
in English dog, in Korean 개
in English cat, in Korean 고양이


In [0]:
dic.values()

dict_values(['사과', '개', '고양이'])