<a href="https://colab.research.google.com/github/yumi-kim/big_data_class/blob/master/%EC%BD%94%EB%94%A9%EC%88%98%EC%97%85_3%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive

In [0]:
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
cd gdrive/My\ Drive

/content/gdrive/My Drive


In [0]:
pwd

'/content/gdrive/My Drive'

In [0]:
cd bbd2019

/content/gdrive/My Drive/bbd2019


In [0]:
cd ../analysis/경상대/2019/8.\ 강의/

/content/gdrive/My Drive/analysis/경상대/2019/8. 강의


In [0]:
cd 2019바이오빅데이터/2019바이오빅데이터\ 수업자료/

/content/gdrive/My Drive/analysis/경상대/2019/8. 강의/2019바이오빅데이터/2019바이오빅데이터 수업자료


In [0]:
ls

 이론수업_1일.gslides   이론수업_2일.gslides  '코딩수업 3일차.ipynb'
 코딩수업_1일.ipynb     코딩수업_2일.ipynb     dictionary.xlsx


In [0]:
pwd

'/content/gdrive/My Drive/analysis/경상대/2019/8. 강의/2019바이오빅데이터/2019바이오빅데이터 수업자료'

In [0]:
# F2 segregation - mendelian inheritance 
# M(homo) x F(homo) -> F1 -> selfing -> F2
# A locus : M(AA) x F(aa)
# F1 : (Aa)
# M (Aa) x F (Aa) -> F2

In [0]:
import random

In [0]:
m = ['A','a'] # yellow seed coat 
f = ['A','a']
F2_locus_gt_list = [] 
for i in range(10000):
  m_allele = random.sample(m,1)
  f_allele = random.sample(f,1)
  F2_locus_gt = m_allele + f_allele 
  F2_locus_gt.sort()
  F2_locus_gt_list.append(''.join(F2_locus_gt))

In [0]:
from collections import Counter
Counter(F2_locus_gt_list)

Counter({'AA': 2499, 'Aa': 5087, 'aa': 2414})

In [0]:
import pandas as pd
df_gt = pd.DataFrame()
df_gt['locus1'] = F2_locus_gt_list
df_gt

In [0]:
m = ['B','b'] # wrinkle or not 
f = ['B','b']
F2_locus_gt_list = [] 
for i in range(10000):
  m_allele = random.sample(m,1)
  f_allele = random.sample(f,1)
  F2_locus_gt = m_allele + f_allele 
  F2_locus_gt.sort()
  F2_locus_gt_list.append(''.join(F2_locus_gt))

In [0]:
df_gt['locus2'] = F2_locus_gt_list

In [0]:
df_gt['merged'] = df_gt.apply(lambda x : x['locus1'] + x['locus2'],axis=1)

In [0]:
df_gt_count = pd.DataFrame(dict(Counter(df_gt['merged'])),index=['Count'])

In [0]:
ys = df_gt_count[['AABB','AABb','AaBB','AaBb']].values.sum()
yw = df_gt_count[['AAbb','Aabb']].values.sum()
gs = df_gt_count[['aaBB','aaBb']].values.sum()
gw = df_gt_count[['aabb']].values.sum()

In [0]:
import numpy as np
gt_count = np.array([ys,yw,gs,gw])

In [0]:
gt_count.astype(float) / gt_count.min()

array([9.40840336, 3.34117647, 3.05714286, 1.        ])

In [0]:
# Hardy-Weinberg equilibrium equation 
# p + q = 1 # allele frequency 
# (p + q)^2 = 1 
# p^2 + 2pq + q^2 = 1 # genotype frequency 

In [0]:
# what if number of alleles was not 2 
# what if allele frequency was not 0.5 

In [0]:
# locus 50 개를 만들어보자 

In [0]:
# 1. locus 당 allele 갯수를 정하자 
np.random.randint(low=2,high=10,size=50)

array([9, 5, 7, 2, 4, 7, 8, 7, 3, 8, 2, 3, 4, 5, 6, 3, 2, 3, 4, 9, 5, 3,
       3, 6, 2, 3, 3, 4, 9, 8, 9, 8, 8, 6, 8, 8, 7, 8, 8, 2, 3, 4, 8, 5,
       2, 5, 6, 2, 2, 3])

In [0]:
# 2. 각 locus 에서 각 allele의 frequency를 바꿔 보자 

In [0]:
p = np.random.random(9)
p = p/sum(p)

In [0]:
p

array([0.15864493, 0.21395621, 0.06906811, 0.17116865, 0.01805329,
       0.05354759, 0.11185605, 0.05492268, 0.14878249])

In [0]:
m = np.random.choice(range(9),p=p)

In [0]:
m

array([1, 3, 6, 7, 1, 3, 3, 8, 3, 0, 0, 4, 5, 1, 8, 3, 3, 1, 6, 1, 6, 1,
       1, 0, 6, 0, 8, 3, 1, 1, 1, 2, 3, 6, 1, 5, 5, 1, 0, 6, 1, 1, 3, 1,
       0, 3, 3, 2, 1, 6])

In [0]:
import numpy as np
import pandas as pd

In [0]:
locus_list = []
for n_allele in np.random.randint(low=2,high=10,size=50):
  p = np.random.random(n_allele)
  p = p/sum(p)
  locus = []
  for i in range(10000):
    m = np.random.choice(range(n_allele),p=p)
    f = np.random.choice(range(n_allele),p=p)
    gt = [str(m),str(f)]
    gt.sort()
    locus.append(''.join(gt))
  locus_list.append(locus)
    
  

In [0]:
df_hw_gt = pd.DataFrame(data=np.array(locus_list))

In [0]:
df_hw_gt.shape

(50, 10000)